### PR TITLE
bump CNI version for the sriov-cni

### PR DESCRIPTION
**Pull request by SchSeba**

### CODE REVIEW

**Comment by SchSeba** [comment]
needed for https://github.com/k8snetworkplumbingwg/sriov-cni/pull/295
https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/pull/65
https://github.com/k8snetworkplumbingwg/multus-cni/pull/1250

**Comment by e0ne** [comment]
@SchSeba please, fix unit-tests to get this merged

**Comment by SchSeba** [comment]
yep I will do it I am waiting for all the other PRs first

**Comment by SchSeba** [comment]
@e0ne @zeeke please take a look small PR :)

**Review by zeeke — APPROVED** [review]
LGTM

**Review by ykulazhenkov — APPROVED** [review]

**Pull request merged**
