### PR TITLE
Remove DPversion from nodeState

### PR DESCRIPTION
**Pull request by SchSeba**
removing this field from the nodeState as we don't need it.

### CODE REVIEW

**Comment by SchSeba** [comment]
we don't need this field it just makes more problems than help.

It was also not really working as we first called in the code the NodeState sync and only after that did we call the device plugin update so the hash was not really right. that also caused another reconcile loop after 5 min from the original one...

```
	sort.Sort(sriovnetworkv1.ByPriority(policyList.Items))
	// Sync SriovNetworkNodeState objects
	if err = r.syncAllSriovNetworkNodeStates(ctx, defaultOpConf, policyList, nodeList); err != nil {
		return reconcile.Result{}, err
	}
	// Sync Sriov device plugin ConfigMap object
	if err = r.syncDevicePluginConfigMap(ctx, defaultOpConf, policyList, nodeList); err != nil {
		return reconcile.Result{}, err
	}
```

**Comment by SchSeba** [comment]
@zeeke @bn222 @e0ne @ykulazhenkov please have a look

**Review by zeeke — APPROVED** [review]
LGTM

**Review by zeeke — APPROVED** [review]
LGTM

**Review by ykulazhenkov — APPROVED** [review]
LGTM

**Review by e0ne — APPROVED** [review]
LGTM

**Pull request merged**
