### PR TITLE
Remove bool ptr

### PR DESCRIPTION
**Pull request by adrianchiris**
Change boolean attribute in SriovOperatorConfig from pointer to concrete.
Main motivation is to simplify code a bit

### CODE REVIEW

**Review by e0ne — APPROVED** [review]
LGTM. Thanks for making our code more simple

**Comment by adrianchiris** [comment]
@SchSeba could you take a look, this is a short one.

**Review by SchSeba — COMMENTED** [review]
general question this will mean that it will be false by default so if someone create the sriovOperatorConfig without this fields it will be false and in case of a pointer it will not exist no?

**Comment by adrianchiris** [comment]
> general question this will mean that it will be false by default so if someone create the sriovOperatorConfig without this fields it will be false and in case of a pointer it will not exist no?

yes, but we have no use-case for a "missing" value.
moreover we always create the default config with values set today.

**Review by SchSeba — APPROVED** [review]
yep you are right I have no problem moving this one out of a pointer and if in the future this is needed we can revert it. from the CRD point of view there is no change so it's transparent to the user

**Pull request merged**
