### PR TITLE
Update go to 1.19

### PR DESCRIPTION
**Pull request by bn222**
Signed-off-by: Balazs Nemeth <bnemeth@redhat.com>

### CODE REVIEW

**Comment by adrianchiris** [comment]
in project dockerfiles point to base image with go1.18 these should be adjusted as well no ?

**Comment by bn222** [comment]
> in project dockerfiles point to base image with go1.18 these should be adjusted as well no ?

Good catch. Updated it.

**Review by adrianchiris — APPROVED** [review]
lgtm

**Review by SchSeba — APPROVED** [review]
/lgtm

**Pull request merged**
