### PR TITLE
e2e: fix e2e test for the sriovnetworknodepolicy

### PR DESCRIPTION
**Pull request by tobiasgiese**
The current Nvidia e2e tests are failing. To resolve this issue, we need to verify only the specified VF range. Without this change, we are mistakenly expecting VFs to have certain values that have not been synchronized by the controller.

### CODE REVIEW

**Review by zeeke — APPROVED** [review]
LGTM

**Comment by tobiasgiese** [comment]
Nvidia e2e test CI failed.
Tested manually on the CI jobs node, should work as expected.

/test-e2e-nvidia-all

**Review by ykulazhenkov — APPROVED** [review]

**Comment by SchSeba** [comment]
Hi @tobiasgiese any plans to run the conformance tests on NVIDIA CI? that suite contain much more tests and validations

**Comment by tobiasgiese** [comment]
> Hi @tobiasgiese any plans to run the conformance tests on NVIDIA CI? that suite contain much more tests and validations

You mean the tests from /test-nvidia-e2e-all? They run successfully already

**Comment by SchSeba** [comment]
I mean running this suite https://github.com/k8snetworkplumbingwg/sriov-network-operator/tree/master/test/conformance 

@tobiasgiese 
Thanks!

**Comment by tobiasgiese** [comment]
@SchSeba the conformance tests will run with the `k8s` job, see
https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/588abb4498fd5e8be86514bb4796ecb8f2dbed22/.github/workflows/test.yml#L156-L157

**Comment by SchSeba** [comment]
yep I know I create that job :P 

the problem is that it runs on virtual hardware (qemu virtual IGB driver) that is why I wanted to ask if NVIDIA can run that on MLX cards it will help us cover the mlx plugin code in CI

**Comment by SchSeba** [comment]
cc @tobiasgiese

**Comment by tobiasgiese** [comment]
> the problem is that it runs on virtual hardware (qemu virtual IGB driver) that is why I wanted to ask if NVIDIA can run that on MLX cards it will help us cover the mlx plugin code in CI

Okay, now I got you :)
I like the idea! Let me discuss this with the team for sure, I'll keep you posted.

**Pull request merged**
