### PR TITLE
fix golangci lint config and goimports

### PR DESCRIPTION
**Pull request by tariq1890**

### CODE REVIEW

**Comment by adrianchiris** [comment]
Thx for working on this improvement !

CI still fails (some files probably still have their imports not aligned)

**Comment by tariq1890** [comment]
@adrianchiris Done

**Review by adrianchiris — APPROVED** [review]
LGTM ! thx for this improvement :-)

**Comment by tariq1890** [comment]
Thanks @adrianchiris !

@e0ne @pliurh @SchSeba  Can you review this PR as well?

**Review by adrianchiris — APPROVED** [review]

**Comment by adrianchiris** [comment]
@Eoghan1232 @SchSeba PTAL.

**Comment by Eoghan1232** [comment]
lgtm! Thanks for these improvements!!

**Review by Eoghan1232 — APPROVED** [review]

**Pull request merged**
