### PR TITLE
Update Ginkgo to v2

### PR DESCRIPTION
**Pull request by liornoy**
This PR updates ginkgo to v2.

Signed-off-by: liornoy <lnoy@redhat.com>

### CODE REVIEW

**Comment by zeeke** [comment]
Hi @liornoy , is it possible to split the commit in 2:
- one for updating go.mod, go.sum and vendor folder
- the second for updating source files

It would make the review much easier

**Comment by liornoy** [comment]
> Hi @liornoy , is it possible to split the commit in 2:
> 
> * one for updating go.mod, go.sum and vendor folder
> * the second for updating source files
> 
> It would make the review much easier

done.

**Comment by zeeke** [comment]
Approved workflow run. @liornoy can you please have a look at the errors? Let me know if you think they are not related to the PR, maybe there are some build flakes.

**Comment by liornoy** [comment]
@zeeke I updated .golangci.yml to solve the lint issues. (adding ginkgo/v2 to the whitelist)
other than that I think the dev-env issue is a flake because I didn't change anything about it, 
and it passes on my cluster.
Can you please approve the workflow for it to run again?

**Review by adrianchiris — APPROVED** [review]

**Review by SchSeba — APPROVED** [review]
I test this one locally and it looks good.

Thanks for the contribution!

**Pull request merged**
