### PR TITLE
Refactor network controller namespace handlers

### PR DESCRIPTION
**Pull request by zeeke**
Move namespace handlers to its own named function in `SriovNetworkReconciler` and `SriovIBNetworkReconciler`. These changes aim to reduce complexity and increase readability.

cc @bn222

### CODE REVIEW

**Comment by bn222** [comment]
LGTM

**Comment by wizhaoredhat** [comment]
lgtm

**Review by SchSeba — APPROVED** [review]
/lgtm

**Review by adrianchiris — APPROVED** [review]
LGTM

**Comment by adrianchiris** [comment]
not sure ocp failure is related to this PR. i see no logs.

re-triggered the job. @zeeke feel free to self merge this one if you see failure is non related  to this PR

**Comment by zeeke** [comment]
All checks are green now. We probably hit a CI flake. Merging

**Pull request merged**
