### PR TITLE
Update controller-runtime to v0.16.3

### PR DESCRIPTION
**Pull request by cgoncalves**
This is an alternative PR to https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/522
Implicitly bumps Kubernetes to 1.28.3.

### CODE REVIEW

**Comment by bn222** [comment]
The human-made changes are lost while doing the vendor update. I would prefer to split up the commit into two: one to bump controller-runtime and one more to fix the working. I know that this means that we have one patch that breaks the build, but since we are committing the vendor changes, I rather pay that price so that we actually see what changes were important.

**Comment by cgoncalves** [comment]
So it happens that this PR is not a complete alternative to https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/522 because it still

**Comment by cgoncalves** [comment]
So it happens that this PR is **not** a complete alternative to https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/522 because it only mitigates the CVE to a degree (see https://github.com/kubernetes/kubernetes/issues/121197).  Nonetheless, this PR still adds important value to the maintainability of the project by updating its dependencies to the latest versions, namely controller-runtime and Kubernetes.

**Review by adrianchiris — APPROVED** [review]

**Comment by bn222** [comment]
I did a `go get -u sigs.k8s.io/controller-runtime/` and also see that fsnotify is updated. How did you update controller-runtime?

**Review by e0ne — APPROVED** [review]
LGTM

**Comment by adrianchiris** [comment]
@cgoncalves could you rebase this one ? we can proceed with merge if everyone is happy

**Review by adrianchiris — APPROVED** [review]

**Comment by bn222** [comment]
LGTM

**Pull request merged**
