### PR TITLE
pass ctx param in controller methods

### PR DESCRIPTION
**Pull request by tariq1890**
The Reconcile method already has ctx in its method signature. It's best practice to pass the same ctx object down the controller method call stack

### CODE REVIEW

**Comment by tariq1890** [comment]
@adrianchiris can we merge this?

**Comment by adrianchiris** [comment]
@tariq1890 the review process requires approval of two maintainers from two different companies.

**Review by adrianchiris — APPROVED** [review]

**Comment by tariq1890** [comment]
Thanks @adrianchiris !

@SchSeba @pliurh Requesting you reviews

**Comment by tariq1890** [comment]
Friendly ping

**Comment by tariq1890** [comment]
??? @SchSeba @pliurh

**Review by zeeke — APPROVED** [review]
LGTM, thanks

**Review by adrianchiris — APPROVED** [review]

**Pull request merged**
