### PR TITLE
Generates random MAC address when effective virtual function MAC addr…

### PR DESCRIPTION
**Pull request by vrindle**
…ess is zero.

This is to set VF effective MAC addresses when the VF effective MAC address is all zero for some vendor NICs.

### CODE REVIEW

**Comment by SchSeba** [comment]
@vrindle can you please fix the commit message.

**Comment by SchSeba** [comment]
Hi @vrindle any update on this PR?

**Comment by vrindle** [comment]
> Hi @vrindle any update on this PR?

Hi Sebastian, I'm in the process of discussing with Pensando engineers, and my manager what is the best way to proceed. Will let you know when this PR will have updates :)

**Comment by vrindle** [comment]
@SchSeba @adrianchiris Pensando engineers have told us they will make the necessary changes in their drivers so therefore changes to the SRIOV network operator are not needed at this time.

**Pull request closed without merging**
