### PR TITLE
Update taints for network-resources-injector and operator-webhook

### PR DESCRIPTION
**Pull request by korroot**
Update node selector for sriov-device-plugin and sriov-network-config-daemon

### CODE REVIEW

**Comment by jjuele** [comment]
Can one of the admins verify this patch?

**Comment by SchSeba** [comment]
Hi @korroot what k8s version are you using?

**Comment by korroot** [comment]
@SchSeba SRIOV operator was not able to spin up properly on Rancher based deployment running v1.24.4 k8s version. The issue we experience is that Rancher adds additional taints on master nodes:

- node-role.kubernetes.io/control-plane: NoSchedule
- node-role.kubernetes.io/etcd: NoExecute

So that network-resources-injector and operator-webhook are not started at all.

**Comment by SchSeba** [comment]
Hi @korroot maybe a better idea here is to add the toleration to these pods?

**Comment by SchSeba** [comment]
Hi @korroot do you still need this PR or we can close it?

**Comment by SchSeba** [comment]
in general we can add the needed tolerations to the yaml and we can extend the node selector if needed but that is not the case with the current implementation if this PR

**Comment by SchSeba** [comment]
closing

**Pull request closed without merging**
