### PR TITLE
Improve operator logging

### PR DESCRIPTION
**Pull request by zeeke**
This PR improves the logging system of the operator:

a. `sigs.k8s.io/controller-runtime/pkg/log/zap` logging system needs a TimeEncoder to be set, so log lines change from:

```
1.6893201843653495e+09	INFO	Starting EventSource	{"controller": "sriovibnetwork"...
```
to 
```
2023-07-14T09:49:58.358957635Z	INFO	Starting EventSource	{"controller":  ...
```

b. Avoid logging in helper functions
c. `renderDevicePluginConfigData()` was logging a growing ResourceList array in a loop, leading to excessive logging when the cluster has 20+ policies.

### CODE REVIEW

**Comment by liornoy** [comment]
lgtm

**Review by cgoncalves — COMMENTED** [review]
LGTM

**Review by e0ne — APPROVED** [review]
LGTM. @zeeke thanks for this improvement!

**Comment by bn222** [comment]
We are using a mix of different loggers. I see there is also `glog.V(2).Infof` in different parts of the code. I'm wondering if this is the right time (same PR) to clean that up too.

**Review by adrianchiris — APPROVED** [review]

**Pull request merged**
