### PR TITLE
Fix issue 471

### PR DESCRIPTION
**Pull request by lmilleri**
It fixes a problem with SRIOV/vDPA configuration:

https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/471

### CODE REVIEW

**Review by SchSeba — APPROVED** [review]
Thanks!

**Review by adrianchiris — APPROVED** [review]

**Review by adrianchiris — CHANGES_REQUESTED** [review]
@lmilleri small nit: please update commit msg with the issue and the change.
instead of linking to gh issue.

**Comment by lmilleri** [comment]
Commit message updated. Thanks

**Review by SchSeba — APPROVED** [review]

**Review by adrianchiris — APPROVED** [review]
Thanks ! ❤️

**Pull request merged**
