### PR TITLE
Add vlanProto parameter

### PR DESCRIPTION
**Pull request by mlguerrero12**
The sriov-cni has a new parameter to set the vlan protocol assign to the vf.

### CODE REVIEW

**Review by zeeke — APPROVED** [review]
LGTM

It looks like failing github actions are not related to this PR, as they fail in other PRs as well

**Comment by mlguerrero12** [comment]
yes, we need to merge the fix in sriov-cni

**Comment by mlguerrero12** [comment]
@adrianchiris, @SchSeba, could you please have a look at this? It's for the recently added vlanProto parameter. Thanks.

**Comment by mlguerrero12** [comment]
@Eoghan1232, could you please have a look at this? It's for the recent vlanProto parameter we added in sriov-cni. Thanks.

**Review by Eoghan1232 — APPROVED** [review]
lgtm

**Pull request merged**
