### PR TITLE
Update base image version to use CentOS 8

### PR DESCRIPTION
**Pull request by e0ne**

### CODE REVIEW

**Review by adrianchiris — APPROVED** [review]

**Review by adrianchiris — APPROVED** [review]

**Review by zshi-redhat — APPROVED** [review]

**Comment by SchSeba** [comment]
@e0ne question will it be possible to use golang:1.17 instead of 1.16?

**Comment by e0ne** [comment]
@SchSeba I'll test with 1.17 and create PR

**Comment by SchSeba** [comment]
@e0ne thanks!

**Pull request merged**
