### PR TITLE
Fix kernel lockdown checking in chroot

### PR DESCRIPTION
**Pull request by mmirecki**

### CODE REVIEW

**Comment by mmirecki** [comment]
/hold
needs verifying

**Review by SchSeba — APPROVED** [review]
/lgtm

**Comment by SchSeba** [comment]
@zshi-redhat @adrianchiris PTAL

**Comment by zshi-redhat** [comment]
@SchSeba @mmirecki  got a question of lock down mode:

One my server, I have:
```
# cat /sys/kernel/security/lockdown
[none] integrity
```
It shows integrity, but mstconfig is able to run on that server.
Do you know why?

**Comment by mmirecki** [comment]
> @SchSeba @mmirecki got a question of lock down mode:
> 
> One my server, I have:
> 
> ```
> # cat /sys/kernel/security/lockdown
> [none] integrity
> ```
> 
> It shows integrity, but mstconfig is able to run on that server.
> Do you know why?

`[none] integrity
`this actually means: None, no lockdown mode
for lockdown mode we will have:
`none [integrity]
`






12:30
none [confidentiality]

**Pull request merged**
