### PR TITLE
small security improvements

### PR DESCRIPTION
**Pull request by SchSeba**
* add runAsNonRoot=true
* add readOnlyRootFilesystem=true
* add allowPrivilegeEscalation=false

for operator network injector and operator webhook

### CODE REVIEW

**Review by zeeke — APPROVED** [review]
LGTM

**Review by ykulazhenkov — APPROVED** [review]
LGTM

**Comment by SchSeba** [comment]
waiting for https://github.com/k8snetworkplumbingwg/network-resources-injector/pull/150

**Review by e0ne — APPROVED** [review]

**Pull request merged**
