### PR TITLE
OVS HWOL: set flow steering mode for eswitch device

### PR DESCRIPTION
**Pull request by zshi-redhat**
Add a knob for steering mode configuration, defaults to dmfs

Signed-off-by: Zenghui Shi <zshi@redhat.com>

### CODE REVIEW

**Comment by pliurh** [comment]
Can you add a description to the commit? IIUC, the `flow_steering_mode` flag is only valid for Mellanox NICs, shall we render this conditionally?

**Comment by adrianchiris** [comment]
> Can you add a description to the commit? IIUC, the flow_steering_mode flag is only valid for Mellanox NICs, shall we render this conditionally?

ATM also the code above it (unbind mlx5_core) is only valid for mlnx NIC so not sure if this bit is required to be rendered conditionally.

LGTM from my side, A bit more context in commit message is appreciated :)

**Review by adrianchiris — APPROVED** [review]

**Comment by zshi-redhat** [comment]
> > Can you add a description to the commit? IIUC, the flow_steering_mode flag is only valid for Mellanox NICs, shall we render this conditionally?

Updated the commit message.
> 
> ATM also the code above it (unbind mlx5_core) is only valid for mlnx NIC so not sure if this bit is required to be rendered conditionally.

Yeah, that's what I'm going to say, I agree that we need to remove the hardcoded driver. I think this can be done in a separate PR.
> 
> LGTM from my side, A bit more context in commit message is appreciated :)

**Comment by pliurh** [comment]
> Updated the commit message.

I cannot see the commit message.

**Comment by zshi-redhat** [comment]
> > Updated the commit message.
> 
> I cannot see the commit message.

I updated in this PR which would appear in the merge log.
Also updated in the commit message this time.

**Pull request merged**
