### PR TITLE
Add NVIDIA Mellanox Technologies MT2894 Family Ethernet Controller ConnectX-6 Lx

### LINKED ISSUE #357: Add NVIDIA Mellanox Technologies MT2894 Family Ethernet Controller ConnectX-6 Lx
Model: NVIDIA Mellanox Technologies MT2894 Family Ethernet Controller ConnectX-6 Lx
Vendor: 15b3
Device: 101f

```
[root@wsfd-advnetlab25 ~]# oc get node -o wide
NAME                 STATUS   ROLES           AGE    VERSION           INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                                                        KERNEL-VERSION                 CONTAINER-RUNTIME
master-0             Ready    master,worker   3d6h   v1.24.0+b62823b   192.168.111.20   <none>        Red Hat Enterprise Linux CoreOS 411.86.202208311835-0 (Ootpa)   4.18.0-372.19.1.el8_6.x86_64   cri-o://1.24.2-6.rhaos4.11.gitb67c16f.el8
master-1             Ready    master,worker   3d6h   v1.24.0+b62823b   192.168.111.21   <none>        Red Hat Enterprise Linux CoreOS 411.86.202208311835-0 (Ootpa)   4.18.0-372.19.1.el8_6.x86_64   cri-o://1.24.2-6.rhaos4.11.gitb67c16f.el8
master-2             Ready    master,worker   3d6h   v1.24.0+b62823b   192.168.111.22   <none>        Red Hat Enterprise Linux CoreOS 411.86.202208311835-0 (Ootpa)   4.18.0-372.19.1.el8_6.x86_64   cri-o://1.24.2-6.rhaos4.11.gitb67c16f.el8
worker-advnetlab23   Ready    worker          3d5h   v1.24.0+b62823b   192.168.111.33   <none>        Red Hat Enterprise Linux CoreOS 411.86.202208311835-0 (Ootpa)   4.18.0-372.19.1.el8_6.x86_64   cri-o://1.24.2-6.rhaos4.11.gitb67c16f.el8
worker-advnetlab24   Ready    worker          3d5h   v1.24.0+b62823b   192.168.111.34   <none>        Red Hat Enterprise Linux CoreOS 411.86.202208311835-0 (Ootpa)   4.18.0-372.19.1.el8_6.x86_64   cri-o://1.24.2-6.rhaos4.11.gitb67c16f.el8
[root@wsfd-advnetlab25 ~]# oc get sriovnetworknodestates.sriovnetwork.openshift.io -n openshift-sriov-network-operator worker-advnetlab23 -o yaml
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodeState
metadata:
  creationTimestamp: "2022-09-07T21:55:58Z"
  generation: 4
  name: worker-advnetlab23
  namespace: openshift-sriov-network-operator
  ownerReferences:
  - apiVersion: sriovnetwork.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: SriovNetworkNodePolicy
    name: default
    uid: dfb6937c-811f-46dd-bef4-4e57c19b12f8
  resourceVersion: "661828"
  uid: 85e7dbd1-fcb9-4a76-9373-e65bb9dd0a16
spec:
  dpConfigVersion: "638783"
  interfaces:
  - name: ens2f0
    numVfs: 11
    pciAddress: 0000:5e:00.0
    vfGroups:
    - deviceType: netdevice
      policyName: policy-mlx-no-switchdev
      resourceName: mlxnicsnoswdev
      vfRange: 0-10
status:
  interfaces:
  - deviceID: "1019"
    driver: mlx5_core
    linkSpeed: -1 Mb/s
    linkType: ETH
    mac: 0c:42:a1:5d:9e:14
    mtu: 1500
    name: ens1f0
    pciAddress: 0000:3b:00.0
    vendor: 15b3
  - deviceID: "1019"
    driver: mlx5_core
    linkSpeed: -1 Mb/s
    linkType: ETH
    mac: 0c:42:a1:5d:9e:15
    mtu: 1500
    name: ens1f1
    pciAddress: 0000:3b:00.1
    vendor: 15b3
  - Vfs:
    - deviceID: 101e
      driver: mlx5_core
      mac: f2:b6:49:78:f4:5c
      mtu: 1500
      name: ens2f0v0
      pciAddress: 0000:5e:00.2
      vendor: 15b3
      vfID: 0
    - deviceID: 101e
      driver: mlx5_core
      mac: 5e:2d:4a:c3:7f:74
      mtu: 1500
      name: ens2f0v1
      pciAddress: 0000:5e:00.3
      vendor: 15b3
      vfID: 1
    - deviceID: 101e
      driver: mlx5_core
      mac: d2:d2:d8:dc:f3:a4
      mtu: 1500
      name: ens2f0v10
      pciAddress: 0000:5e:01.4
      vendor: 15b3
      vfID: 10
    - deviceID: 101e
      driver: mlx5_core
      mac: 6e:b2:6e:96:9e:2d
      mtu: 1500
      name: ens2f0v2
      pciAddress: 0000:5e:00.4
      vendor: 15b3
      vfID: 2
    - deviceID: 101e
      driver: mlx5_core
      pciAddress: 0000:5e:00.5
      vendor: 15b3
      vfID: 3
    - deviceID: 101e
      driver: mlx5_core
      mac: 6a:e7:95:93:68:51
      mtu: 1500
      name: ens2f0v4
      pciAddress: 0000:5e:00.6
      vendor: 15b3
      vfID: 4
    - deviceID: 101e
      driver: mlx5_core
      mac: 06:2c:08:79:3f:60
      mtu: 1500
      name: ens2f0v5
      pciAddress: 0000:5e:00.7
      vendor: 15b3
      vfID: 5
    - deviceID: 101e
      driver: mlx5_core
      mac: 5e:f2:ba:fc:81:3d
      mtu: 1500
      name: ens2f0v6
      pciAddress: 0000:5e:01.0
      vendor: 15b3
      vfID: 6
    - deviceID: 101e
      driver: mlx5_core
      mac: 42:4b:fc:c6:5d:bc
      mtu: 1500
      name: ens2f0v7
      pciAddress: 0000:5e:01.1
      vendor: 15b3
      vfID: 7
    - deviceID: 101e
      driver: mlx5_core
      mac: ea:eb:4d:2c:47:7b
      mtu: 1500
      name: ens2f0v8
      pciAddress: 0000:5e:01.2
      vendor: 15b3
      vfID: 8
    - deviceID: 101e
      driver: mlx5_core
      mac: da:10:38:0c:09:47
      mtu: 1500
      name: ens2f0v9
      pciAddress: 0000:5e:01.3
      vendor: 15b3
      vfID: 9
    deviceID: 101f
    driver: mlx5_core
    eSwitchMode: legacy
    linkSpeed: 25000 Mb/s
    linkType: ETH
    mac: 10:70:fd:5d:77:d4
    mtu: 1500
    name: ens2f0
    numVfs: 11
    pciAddress: 0000:5e:00.0
    totalvfs: 11
    vendor: 15b3
  - deviceID: 101f
    driver: mlx5_core
    linkSpeed: 25000 Mb/s
    linkType: ETH
    mac: 10:70:fd:5d:77:d5
    mtu: 1500
    name: ens2f1
    pciAddress: 0000:5e:00.1
    totalvfs: 11
    vendor: 15b3
  - deviceID: 159b
    driver: ice
    eSwitchMode: legacy
    linkSpeed: 25000 Mb/s
    linkType: ETH
    mac: b4:96:91:a5:c9:a8
    mtu: 1500
    name: ens3f0
    pciAddress: 0000:d8:00.0
    totalvfs: 128
    vendor: "8086"
  - deviceID: 159b
    driver: ice
    eSwitchMode: legacy
    linkSpeed: 25000 Mb/s
    linkType: ETH
    mac: b4:96:91:a5:c9:a9
    mtu: 1500
    name: ens3f1
    pciAddress: 0000:d8:00.1
    totalvfs: 128
    vendor: "8086"
  syncStatus: Succeeded
[root@wsfd-advnetlab25 ~]# oc get pods
NAME             READY   STATUS    RESTARTS   AGE
test-pod-node1   1/1     Running   0          45h
test-pod-node2   1/1     Running   0          46h
[root@wsfd-advnetlab25 ~]# oc exec -it test-pod-node1 -- /bin/bash
bash-5.0# ls /sys/bus/pci/devices/0000\:5e\:00.5/net/
net1
bash-5.0# cat /sys/bus/pci/devices/0000\:5e\:00.5/uevent 
DRIVER=mlx5_core
PCI_CLASS=20000
PCI_ID=15B3:101E
PCI_SUBSYS_ID=15B3:0001
PCI_SLOT_NAME=0000:5e:00.5
MODALIAS=pci:v000015B3d0000101Esv000015B3sd00000001bc02sc00i00
bash-5.0# cat /sys/bus/pci/devices/0000\:5e\:00.5/physfn/uevent
DRIVER=mlx5_core
PCI_CLASS=20000
PCI_ID=15B3:101F
PCI_SUBSYS_ID=15B3:0001
PCI_SLOT_NAME=0000:5e:00.0
MODALIAS=pci:v000015B3d0000101Fsv000015B3sd00000001bc02sc00i00
```

Tested:
sriov-network-operator can discover the device.
sriov-network-operator and sriov-cni can configure the device.
As shown above in the test pods, workloads can be run using the VF.

### PR DESCRIPTION
**Pull request by wizhaoredhat**
Fixes #357

Signed-off-by: William Zhao <wizhao@redhat.com>

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
@adrianchiris FYI

**Comment by adrianchiris** [comment]
@wizhaoredhat did you run connectx6 lx with openshift ?

**Comment by wizhaoredhat** [comment]
> @wizhaoredhat did you run connectx6 lx with openshift ?

@adrianchiris 
Yes, I did.

**Comment by adrianchiris** [comment]
super ! thx @wizhaoredhat

**Review by adrianchiris — APPROVED** [review]

**Comment by wizhaoredhat** [comment]
@adrianchiris Could you merge this PR as well?

**Comment by SchSeba** [comment]
Hi @wizhaoredhat can you try to use the u/s sriov-config-daemon image?

ghcr.io/k8snetworkplumbingwg/sriov-network-operator-config-daemon:v1.2.0

If I remember the problem was centos stream don't have the right version of mstflint to support this card.

**Review by e0ne — APPROVED** [review]
/LGTM

**Comment by SchSeba** [comment]
https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/317

**Comment by wizhaoredhat** [comment]
> ghcr.io/k8snetworkplumbingwg/sriov-network-operator-config-daemon:v1.2.0

@SchSeba 

Looks good to me:
[root@wsfd-advnetlab25 ~]# oc exec -it sriov-network-config-daemon-m9zh7 -n openshift-sriov-network-operator -c sriov-network-config-daemon -- /bin/bash
[root@worker-advnetlab23 /]# mstconfig -d 5e:00.0 q

Device #1:
----------

Device type:    ConnectX6LX     
Name:           MCX631102AN-ADA_Ax
Description:    ConnectX-6 Lx EN adapter card; 25GbE ; Dual-port SFP28; PCIe 4.0 x8; No Crypto
Device:         5e:00.0   
[root@worker-advnetlab23 /]# mstflint -v
mstflint, mstflint 4.19.0, built on Apr  7 2022, 23:09:23. Git SHA Hash: 2b02298
[root@worker-advnetlab23 /]# cat /etc/redhat-release 
CentOS Stream release 8
[root@wsfd-advnetlab25 ~]# oc describe pod sriov-network-config-daemon-m9zh7 -n openshift-sriov-network-operator 
...
  sriov-network-config-daemon:
    Container ID:  cri-o://2b5f7f3fd6b667d73ef10093852304eaa26cca98ff26b0c34b36789f9a91d178
    Image:         ghcr.io/k8snetworkplumbingwg/sriov-network-operator-config-daemon:v1.2.0
    Image ID:      ghcr.io/k8snetworkplumbingwg/sriov-network-operator-config-daemon@sha256:018fb75722a5287bcd74c4b6aac27e3480bad1c39465873d2ecc62cd04c92001
...
[root@wsfd-advnetlab25 ~]# oc logs sriov-network-config-daemon-m9zh7 -n openshift-sriov-network-operator -c sriov-network-config-daemon
...
I0912 19:07:59.445256 1624833 utils.go:749] RunCommand(): 
Device #1:
----------

Device type:    ConnectX6LX     
Name:           MCX631102AN-ADA_Ax
Description:    ConnectX-6 Lx EN adapter card; 25GbE ; Dual-port SFP28; PCIe 4.0 x8; No Crypto
Device:         0000:5e:00.0    

Configurations:                              Default         Current         Next Boot
         MEMIC_BAR_SIZE                      0               0               0               
         MEMIC_SIZE_LIMIT                    _256KB(1)       _256KB(1)       _256KB(1)       
         HOST_CHAINING_MODE                  DISABLED(0)     DISABLED(0)     DISABLED(0)     
         HOST_CHAINING_CACHE_DISABLE         False(0)        False(0)        False(0)        
         HOST_CHAINING_DESCRIPTORS           Array[0..7]     Array[0..7]     Array[0..7]     
         HOST_CHAINING_TOTAL_BUFFER_SIZE     Array[0..7]     Array[0..7]     Array[0..7]     
         FLEX_PARSER_PROFILE_ENABLE          0               0               0               
         PROG_PARSE_GRAPH                    False(0)        False(0)        False(0)        
         FLEX_IPV4_OVER_VXLAN_PORT           0               0               0               
         ROCE_NEXT_PROTOCOL                  254             254             254             
         ESWITCH_HAIRPIN_DESCRIPTORS         Array[0..7]     Array[0..7]     Array[0..7]     
         ESWITCH_HAIRPIN_TOT_BUFFER_SIZE     Array[0..7]     Array[0..7]     Array[0..7]     
         PF_BAR2_SIZE                        0               0               0               
         NON_PREFETCHABLE_PF_BAR             False(0)        False(0)        False(0)        
         VF_VPD_ENABLE                       False(0)        False(0)        False(0)        
         PF_NUM_PF_MSIX_VALID                False(0)        False(0)        False(0)        
         PER_PF_NUM_SF                       False(0)        False(0)        False(0)        
         STRICT_VF_MSIX_NUM                  False(0)        False(0)        False(0)        
         VF_NODNIC_ENABLE                    False(0)        False(0)        False(0)        
         NUM_PF_MSIX_VALID                   True(1)         True(1)         True(1)         
*        NUM_OF_VFS                          8               11              11              
         NUM_OF_PF                           2               2               2               
         PF_BAR2_ENABLE                      False(0)        False(0)        False(0)        
         SRIOV_EN                            True(1)         True(1)         True(1)         
         PF_LOG_BAR_SIZE                     5               5               5               
         VF_LOG_BAR_SIZE                     0               0               0               
         NUM_PF_MSIX                         63              63              63              
         NUM_VF_MSIX                         11              11              11              
         INT_LOG_MAX_PAYLOAD_SIZE            AUTOMATIC(0)    AUTOMATIC(0)    AUTOMATIC(0)    
         PCIE_CREDIT_TOKEN_TIMEOUT           0               0               0               
         ACCURATE_TX_SCHEDULER               False(0)        False(0)        False(0)        
         PARTIAL_RESET_EN                    False(0)        False(0)        False(0)        
         RESET_WITH_HOST_ON_ERRORS           False(0)        False(0)        False(0)        
         PCI_DOWNSTREAM_PORT_OWNER           Array[0..15]    Array[0..15]    Array[0..15]    
         CQE_COMPRESSION                     BALANCED(0)     BALANCED(0)     BALANCED(0)     
         IP_OVER_VXLAN_EN                    False(0)        False(0)        False(0)        
         MKEY_BY_NAME                        False(0)        False(0)        False(0)        
         PRIO_TAG_REQUIRED_EN                False(0)        False(0)        False(0)        
         UCTX_EN                             True(1)         True(1)         True(1)         
         REAL_TIME_CLOCK_ENABLE              False(0)        False(0)        False(0)        
         RDMA_SELECTIVE_REPEAT_EN            False(0)        False(0)        False(0)        
         PCI_ATOMIC_MODE                     PCI_ATOMIC_DISABLED_EXT_ATOMIC_ENABLED(0) PCI_ATOMIC_DISABLED_EXT_ATOMIC_ENABLED(0) PCI_ATOMIC_DISABLED_EXT_ATOMIC_ENABLED(0)
         TUNNEL_ECN_COPY_DISABLE             False(0)        False(0)        False(0)        
         LRO_LOG_TIMEOUT0                    6               6               6               
         LRO_LOG_TIMEOUT1                    7               7               7               
         LRO_LOG_TIMEOUT2                    8               8               8               
         LRO_LOG_TIMEOUT3                    13              13              13              
         LOG_TX_PSN_WINDOW                   7               7               7               
         LOG_MAX_OUTSTANDING_WQE             7               7               7               
         TUNNEL_IP_PROTO_ENTROPY_DISABLE     False(0)        False(0)        False(0)        
         ICM_CACHE_MODE                      DEVICE_DEFAULT(0) DEVICE_DEFAULT(0) DEVICE_DEFAULT(0)
         TX_SCHEDULER_BURST                  0               0               0               
         LOG_DCR_HASH_TABLE_SIZE             11              11              11              
         DCR_LIFO_SIZE                       16384           16384           16384           
         ROCE_CC_PRIO_MASK_P1                255             255             255             
         ROCE_CC_PRIO_MASK_P2                255             255             255             
         CLAMP_TGT_RATE_AFTER_TIME_INC_P1    True(1)         True(1)         True(1)         
         CLAMP_TGT_RATE_P1                   False(0)        False(0)        False(0)        
         RPG_TIME_RESET_P1                   300             300             300             
         RPG_BYTE_RESET_P1                   32767           32767           32767           
         RPG_THRESHOLD_P1                    1               1               1               
         RPG_MAX_RATE_P1                     0               0               0               
         RPG_AI_RATE_P1                      5               5               5               
         RPG_HAI_RATE_P1                     50              50              50              
         RPG_GD_P1                           11              11              11              
         RPG_MIN_DEC_FAC_P1                  50              50              50              
         RPG_MIN_RATE_P1                     1               1               1               
         RATE_TO_SET_ON_FIRST_CNP_P1         0               0               0               
         DCE_TCP_G_P1                        1019            1019            1019            
         DCE_TCP_RTT_P1                      1               1               1               
         RATE_REDUCE_MONITOR_PERIOD_P1       4               4               4               
         INITIAL_ALPHA_VALUE_P1              1023            1023            1023            
         MIN_TIME_BETWEEN_CNPS_P1            4               4               4               
         CNP_802P_PRIO_P1                    6               6               6               
         CNP_DSCP_P1                         48              48              48              
         CLAMP_TGT_RATE_AFTER_TIME_INC_P2    True(1)         True(1)         True(1)         
         CLAMP_TGT_RATE_P2                   False(0)        False(0)        False(0)        
         RPG_TIME_RESET_P2                   300             300             300             
         RPG_BYTE_RESET_P2                   32767           32767           32767           
         RPG_THRESHOLD_P2                    1               1               1               
         RPG_MAX_RATE_P2                     0               0               0               
         RPG_AI_RATE_P2                      5               5               5               
         RPG_HAI_RATE_P2                     50              50              50              
         RPG_GD_P2                           11              11              11              
         RPG_MIN_DEC_FAC_P2                  50              50              50              
         RPG_MIN_RATE_P2                     1               1               1               
         RATE_TO_SET_ON_FIRST_CNP_P2         0               0               0               
         DCE_TCP_G_P2                        1019            1019            1019            
         DCE_TCP_RTT_P2                      1               1               1               
         RATE_REDUCE_MONITOR_PERIOD_P2       4               4               4               
         INITIAL_ALPHA_VALUE_P2              1023            1023            1023            
         MIN_TIME_BETWEEN_CNPS_P2            4               4               4               
         CNP_802P_PRIO_P2                    6               6               6               
         CNP_DSCP_P2                         48              48              48              
         LLDP_NB_DCBX_P1                     False(0)        False(0)        False(0)        
         LLDP_NB_RX_MODE_P1                  OFF(0)          OFF(0)          OFF(0)          
         LLDP_NB_TX_MODE_P1                  OFF(0)          OFF(0)          OFF(0)          
         LLDP_NB_DCBX_P2                     False(0)        False(0)        False(0)        
         LLDP_NB_RX_MODE_P2                  OFF(0)          OFF(0)          OFF(0)          
         LLDP_NB_TX_MODE_P2                  OFF(0)          OFF(0)          OFF(0)          
         DCBX_IEEE_P1                        True(1)         True(1)         True(1)         
         DCBX_CEE_P1                         True(1)         True(1)         True(1)         
         DCBX_WILLING_P1                     True(1)         True(1)         True(1)         
         DCBX_IEEE_P2                        True(1)         True(1)         True(1)         
         DCBX_CEE_P2                         True(1)         True(1)         True(1)         
         DCBX_WILLING_P2                     True(1)         True(1)         True(1)         
         KEEP_ETH_LINK_UP_P1                 True(1)         True(1)         True(1)         
         KEEP_IB_LINK_UP_P1                  False(0)        False(0)        False(0)        
         KEEP_LINK_UP_ON_BOOT_P1             False(0)        False(0)        False(0)        
         KEEP_LINK_UP_ON_STANDBY_P1          False(0)        False(0)        False(0)        
         DO_NOT_CLEAR_PORT_STATS_P1          False(0)        False(0)        False(0)        
         AUTO_POWER_SAVE_LINK_DOWN_P1        False(0)        False(0)        False(0)        
         KEEP_ETH_LINK_UP_P2                 True(1)         True(1)         True(1)         
         KEEP_IB_LINK_UP_P2                  False(0)        False(0)        False(0)        
         KEEP_LINK_UP_ON_BOOT_P2             False(0)        False(0)        False(0)        
         KEEP_LINK_UP_ON_STANDBY_P2          False(0)        False(0)        False(0)        
         DO_NOT_CLEAR_PORT_STATS_P2          False(0)        False(0)        False(0)        
         AUTO_POWER_SAVE_LINK_DOWN_P2        False(0)        False(0)        False(0)        
         NUM_OF_VL_P1                        _4_VLs(3)       _4_VLs(3)       _4_VLs(3)       
         NUM_OF_TC_P1                        _8_TCs(0)       _8_TCs(0)       _8_TCs(0)       
         NUM_OF_PFC_P1                       8               8               8               
         VL15_BUFFER_SIZE_P1                 0               0               0               
         NUM_OF_VL_P2                        _4_VLs(3)       _4_VLs(3)       _4_VLs(3)       
         NUM_OF_TC_P2                        _8_TCs(0)       _8_TCs(0)       _8_TCs(0)       
         NUM_OF_PFC_P2                       8               8               8               
         VL15_BUFFER_SIZE_P2                 0               0               0               
         DUP_MAC_ACTION_P1                   LAST_CFG(0)     LAST_CFG(0)     LAST_CFG(0)     
         UNKNOWN_UPLINK_MAC_FLOOD_P1         False(0)        False(0)        False(0)        
         SRIOV_IB_ROUTING_MODE_P1            LID(1)          LID(1)          LID(1)          
         IB_ROUTING_MODE_P1                  LID(1)          LID(1)          LID(1)          
         DUP_MAC_ACTION_P2                   LAST_CFG(0)     LAST_CFG(0)     LAST_CFG(0)     
         UNKNOWN_UPLINK_MAC_FLOOD_P2         False(0)        False(0)        False(0)        
         SRIOV_IB_ROUTING_MODE_P2            LID(1)          LID(1)          LID(1)          
         IB_ROUTING_MODE_P2                  LID(1)          LID(1)          LID(1)          
         PF_TOTAL_SF                         0               0               0               
         PF_SF_BAR_SIZE                      0               0               0               
         PF_NUM_PF_MSIX                      63              63              63              
*        ROCE_CONTROL                        ROCE_ENABLE(2)  DEVICE_DEFAULT(0) ROCE_ENABLE(2)  
         PCI_WR_ORDERING                     per_mkey(0)     per_mkey(0)     per_mkey(0)     
         MULTI_PORT_VHCA_EN                  False(0)        False(0)        False(0)        
         PORT_OWNER                          True(1)         True(1)         True(1)         
         ALLOW_RD_COUNTERS                   True(1)         True(1)         True(1)         
         RENEG_ON_CHANGE                     True(1)         True(1)         True(1)         
         TRACER_ENABLE                       True(1)         True(1)         True(1)         
         IP_VER                              IPv4(0)         IPv4(0)         IPv4(0)         
         BOOT_UNDI_NETWORK_WAIT              0               0               0               
         UEFI_HII_EN                         True(1)         True(1)         True(1)         
         BOOT_DBG_LOG                        False(0)        False(0)        False(0)        
         UEFI_LOGS                           DISABLED(0)     DISABLED(0)     DISABLED(0)     
         BOOT_VLAN                           1               1               1               
         LEGACY_BOOT_PROTOCOL                PXE(1)          PXE(1)          PXE(1)          
         BOOT_RETRY_CNT                      NONE(0)         NONE(0)         NONE(0)         
         BOOT_INTERRUPT_DIS                  False(0)        False(0)        False(0)        
         BOOT_LACP_DIS                       True(1)         True(1)         True(1)         
         BOOT_VLAN_EN                        False(0)        False(0)        False(0)        
         BOOT_PKEY                           0               0               0               
         P2P_ORDERING_MODE                   DEVICE_DEFAULT(0) DEVICE_DEFAULT(0) DEVICE_DEFAULT(0)
         DYNAMIC_VF_MSIX_TABLE               False(0)        False(0)        False(0)        
         EXP_ROM_UEFI_ARM_ENABLE             True(1)         True(1)         True(1)         
         EXP_ROM_UEFI_x86_ENABLE             True(1)         True(1)         True(1)         
         EXP_ROM_PXE_ENABLE                  True(1)         True(1)         True(1)         
         ADVANCED_PCI_SETTINGS               False(0)        False(0)        False(0)        
         SAFE_MODE_THRESHOLD                 10              10              10              
         SAFE_MODE_ENABLE                    True(1)         True(1)         True(1)         
The '*' shows parameters with next value different from default/current value.
, %!s(<nil>)
I0912 19:07:59.445320 1624833 mellanox_plugin.go:277] mellanox-plugin parseMstconfigOutput(): Attributes [NUM_OF_VFS SRIOV_EN LINK_TYPE_P1 LINK_TYPE_P2]
I0912 19:07:59.445397 1624833 mellanox_plugin.go:257] mellanox-plugin mlnxNicFromMap() map[NUM_OF_VFS:11 SRIOV_EN:True(1)]
I0912 19:07:59.445408 1624833 mellanox_plugin.go:306] mellanox-plugin getLinkType(): linkType 
W0912 19:07:59.445413 1624833 mellanox_plugin.go:315] mellanox-plugin getLinkType(): LINK_TYPE_P* attribute was not found
I0912 19:07:59.445417 1624833 mellanox_plugin.go:257] mellanox-plugin mlnxNicFromMap() map[NUM_OF_VFS:11 SRIOV_EN:True(1)]
I0912 19:07:59.445421 1624833 mellanox_plugin.go:306] mellanox-plugin getLinkType(): linkType 
W0912 19:07:59.445425 1624833 mellanox_plugin.go:315] mellanox-plugin getLinkType(): LINK_TYPE_P* attribute was not found
I0912 19:07:59.445428 1624833 mellanox_plugin.go:300] mellanox-plugin isDualPort(): pciAddress 0000:5e:00.0
I0912 19:07:59.445433 1624833 mellanox_plugin.go:341] mellanox-plugin getOtherPortSpec(): pciAddress 0000:5e:00.0
I0912 19:07:59.445438 1624833 mellanox_plugin.go:321] mellanox-plugin isLinkTypeRequireChange(): device 0000:5e:00.0
...
```

**Comment by adrianchiris** [comment]
>mellanox-plugin getLinkType(): LINK_TYPE_P* attribute was not found

thats expected since ConnectX6 Lx is ethernet only

**Comment by SchSeba** [comment]
@adrianchiris will this PR also close https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/317 ?

**Comment by adrianchiris** [comment]
@SchSeba yep. seems like centos repos were updated.

**Review by SchSeba — APPROVED** [review]

**Pull request merged**
