### PR TITLE
Avoid recording multiple events

### PR DESCRIPTION
**Pull request by adrianchiris**
In case update operation fail in node status writer we should not record an event.

move event sending logic to its own method
and call it after status has been successfully updated.

### CODE REVIEW

**Comment by adrianchiris** [comment]
@rollandf PTAL.

still need to test this one on my setup.

**Review by rollandf — APPROVED** [review]
LGTM

**Review by zeeke — APPROVED** [review]
LGTM

Good catch

**Comment by adrianchiris** [comment]
This is working as expected.

There is another issue with roles in the operator following events introduction, ill send fix in a separarte PR.

**Pull request merged**
