### PR TITLE
Fix stylecheck issues

### PR DESCRIPTION
**Pull request by rollandf**
This commit fixes issues found by
`golangci-lint run --disable-all -E stylecheck`

Signed-off-by: Fred Rolland <frolland@nvidia.com>

### CODE REVIEW

**Review by adrianchiris — APPROVED** [review]

**Comment by SchSeba** [comment]
@rollandf please rebase this PR

**Comment by rollandf** [comment]
@SchSeba rebased

**Comment by Eoghan1232** [comment]
LGTM

**Comment by adrianchiris** [comment]
Thanks for the Review !

**Pull request merged**
