### PR TITLE
feat: support extraDeploy field in helm chart

### PR DESCRIPTION
**Pull request by fengxsong**
This PR made the following changes:

1. Remove duplicate environment variable `METRICS_EXPORTER_SECRET_NAME` ~~and correct the `METRICS_EXPORTER_PORT` environment variable~~.

2. Support adding additional deployment objects in the Helm chart, such as `SriovNetworkNodePolicy` and `SriovNetwork`, along with the release.

### CODE REVIEW

**Comment by adrianchiris** [comment]
im not sure we should support deploying arbitrary "things" as part of the chart.

my take is that the chart should deploy the minimal set of components that are required for sriov network operator to work.
other CRs should be deployed as a post install/update step.

**Comment by fengxsong** [comment]
@zeeke I have reverted this part of the modification back.

> my take is that the chart should deploy the minimal set of components that are required for sriov network operator to work.

@adrianchiris yes, I'm agree with that, keeping deployments as simple as possible is a good point, but sometimes it might be better to provide simple functionality extensions.

In the scenario where we manage cluster deployments using GitOps, I prefer a single deployment that includes everything needed rather than applying additional configurations after deployment.

**Comment by adrianchiris** [comment]
Hi @fengxsong we discussed this in today's community meeting. we are OK with this change. please add a disclaimer in helm chart README that whatever is deployed via this value is the user's responsibility.

**Review by adrianchiris — APPROVED** [review]

**Review by SchSeba — APPROVED** [review]
LGTM

**Pull request merged**
