### PR TITLE
Update golang to v1.17

### PR DESCRIPTION
**Pull request by e0ne**
This patch introduces following changes:
    * explicitly set go version to v1.17 in GitHub actions
    * updates go.mod file and vendored packages
    * updates go version in Dockerfiles
    * uses 'go install' instead of 'go get' [1]

    [1] https://go.dev/doc/go-get-install-deprecation

### CODE REVIEW

**Comment by SchSeba** [comment]
Thanks for the contribution!

/lgtm

**Comment by adrianchiris** [comment]
@e0ne where are you using go install instead of go get ?

i see:
 https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/4baf8e5012641983ff732ecacd4ffc9c7efbdd76/Makefile#L156

**Comment by e0ne** [comment]
@adrianchiris I updated PR description. It requires more investigation how to install controller-gen using 'go install'

**Comment by adrianchiris** [comment]
looking at Makefile it just replacing go get with go install in `go-get-tool` mind trying it out ? :)

**Comment by e0ne** [comment]
> looking at Makefile it just replacing go get with go install in `go-get-tool` mind trying it out ? :)

Unfortunately, it's not  so easy:
```
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
go install: sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1: cannot query module due to -mod=vendor
make: *** [Makefile:149: controller-gen] Error 1
```

Simple version bump doesn't work for me. I didn't dig deep into this issue, so I left this change to another PR

**Comment by e0ne** [comment]
@adrianchiris 'go install' is now used.

**Comment by adrianchiris** [comment]
@e0ne it seems to fail trying to install kustomize

i will open an issue on it, we will need to deal with before updating to go 1.18.

**Comment by adrianchiris** [comment]
@e0ne  could you rebase and fix conflicts ?

**Comment by e0ne** [comment]
@adrianchiris  done

**Review by adrianchiris — APPROVED** [review]

**Comment by adrianchiris** [comment]
@SchSeba @zshi-redhat  can we merge this ?

**Pull request merged**
