### PR TITLE
Update machine config operator

### PR DESCRIPTION
**Pull request by SalDaniele**
Update machine config operator to remove dependency on goproxy.

go mod tidy && go mod vendor

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
LGTM

**Comment by zeeke** [comment]
CI is broken due to the webhook not able to start ([logs](https://productionresultssa8.blob.core.windows.net/actions-results/268c5f8f-541f-4185-9ada-5c36a0fd1ce9/workflow-job-run-375e03a6-b785-5e96-2c8d-799b48e5eff1/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-06-05T07%3A25%3A20Z&sig=Vw%2BrQ%2F%2BLUjfVIZm0CT2UzaIRPuRl5BRWz23KaZKBav8%3D&ske=2024-06-05T16%3A04%3A47Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-06-05T04%3A04%3A47Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-06-05T07%3A15%3A15Z&sv=2023-11-03))

```
2024-06-04T21:27:05.8888659Z ==== START logs for container webhook-server of pod sriov-network-operator/operator-webhook-9jvn9 ====
2024-06-04T21:27:05.8888829Z Error: unknown flag: --alsologtostderr
2024-06-04T21:27:05.8888907Z Usage:
2024-06-04T21:27:05.8889117Z   sriov-network-operator-webhook start [flags]
2024-06-04T21:27:05.8889127Z 
2024-06-04T21:27:05.8889207Z Flags:
2024-06-04T21:27:05.8889668Z       --enable-http2                  If HTTP/2 should be enabled for the metrics and webhook servers.
2024-06-04T21:27:05.8889876Z   -h, --help                          help for start
2024-06-04T21:27:05.8890277Z       --port int                      Secure port that the webhook listens on (default 443)
2024-06-04T21:27:05.8890991Z       --tls-cert-file string          File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert).
2024-06-04T21:27:05.8891592Z       --tls-private-key-file string   File containing the default x509 private key matching --tls-cert-file.
2024-06-04T21:27:05.8891600Z 
2024-06-04T21:27:05.8891684Z Global Flags:
2024-06-04T21:27:05.8892792Z       --zap-devel                         Development Mode defaults(encoder=consoleEncoder,logLevel=Debug,stackTraceLevel=Warn). Production Mode defaults(encoder=jsonEncoder,logLevel=Info,stackTraceLevel=Error) (default true)
2024-06-04T21:27:05.8893207Z       --zap-encoder encoder               Zap log encoding (one of 'json' or 'console')
2024-06-04T21:27:05.8894288Z       --zap-log-level level               Zap Level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error', or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
2024-06-04T21:27:05.8894995Z       --zap-stacktrace-level level        Zap Level at and above which stacktraces are captured (one of 'info', 'error', 'panic').
2024-06-04T21:27:05.8895774Z       --zap-time-encoding time-encoding   Zap time encoding (one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'). Defaults to 'epoch'.
2024-06-04T21:27:05.8895781Z 
2024-06-04T21:27:05.8896242Z ==== END logs for container webhook-server of pod sriov-network-operator/operator-webhook-9jvn9 ====
```



any idea of how it happened? maybe one of the bumped dependency broke it?

**Comment by SalDaniele** [comment]
Hmm let me take a look. Its not obvious to me why bumping this dependencies would cause an unknown flag error to sriov-network-operator-webhook.

**Comment by SalDaniele** [comment]
It looks like some of the package updates are responsible for the missing flags

Before upgrades:

`Run Webhook Daemon which validates/mutates the Custom Resource of the SR-IoV Network Operator

Usage:
  sriov-network-operator-webhook [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  start       Starts Webhook Daemon

Flags:
      --alsologtostderr                   log to standard error as well as files
  -h, --help                              help for sriov-network-operator-webhook
      --log_backtrace_at traceLocations   when logging hits line file:N, emit a stack trace
      --log_dir string                    If non-empty, write log files in this directory
      --log_link string                   If non-empty, add symbolic links in this directory to the log files
      --logbuflevel int                   Buffer log messages logged at this level or lower (-1 means don't buffer; 0 means buffer INFO only; ...). Has limited applicability on non-prod platforms.
      --logtostderr                       log to standard error instead of files
      --stderrthreshold severityFlag      logs at or above this threshold go to stderr (default 2)
  -v, --v Level                           log level for V logs
      --vmodule vModuleFlag               comma-separated list of pattern=N settings for file-filtered logging
      --zap-devel                         Development Mode defaults(encoder=consoleEncoder,logLevel=Debug,stackTraceLevel=Warn). Production Mode defaults(encoder=jsonEncoder,logLevel=Info,stackTraceLevel=Error) (default true)
      --zap-encoder encoder               Zap log encoding (one of 'json' or 'console')
      --zap-log-level level               Zap Level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error', or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
      --zap-stacktrace-level level        Zap Level at and above which stacktraces are captured (one of 'info', 'error', 'panic').
      --zap-time-encoding time-encoding   Zap time encoding (one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'). Defaults to 'epoch'.
`

After Upgrades:

`Run Webhook Daemon which validates/mutates the Custom Resource of the SR-IoV Network Operator

Usage:
  sriov-network-operator-webhook [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  start       Starts Webhook Daemon

Flags:
  -h, --help                              help for sriov-network-operator-webhook
      --zap-devel                         Development Mode defaults(encoder=consoleEncoder,logLevel=Debug,stackTraceLevel=Warn). Production Mode defaults(encoder=jsonEncoder,logLevel=Info,stackTraceLevel=Error) (default true)
      --zap-encoder encoder               Zap log encoding (one of 'json' or 'console')
      --zap-log-level level               Zap Level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error', or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
      --zap-stacktrace-level level        Zap Level at and above which stacktraces are captured (one of 'info', 'error', 'panic').
      --zap-time-encoding time-encoding   Zap time encoding (one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'). Defaults to 'epoch'.

Use "sriov-network-operator-webhook [command] --help" for more information about a command.
`

**Comment by SalDaniele** [comment]
@zeeke PTAL. Resolved the issues with the missing flags,  we removed an indirect dependency on github.com/golang/glog by updating the machine config operator. This package provides an init() method which sets a number of flags such as alsologtostderr.

K8s test is passing now, I believe the OCP failure is unrelated to the PR

**Comment by zeeke** [comment]
> @zeeke PTAL. Resolved the issues with the missing flags, we removed an indirect dependency on github.com/golang/glog by updating the machine config operator. This package provides an init() method which sets a number of flags such as alsologtostderr.
> 
> K8s test is passing now, I believe the OCP failure is unrelated to the PR

Thanks for going deep here. LGTM

**Review by zeeke — APPROVED** [review]

**Comment by SalDaniele** [comment]
Looks like the ocp tests are failing still, I believe this is unrelated

```
+ internal_registry=image-registry.openshift-image-registry.svc:5000
++ jq '."image-registry.openshift-image-registry.svc:5000".password' registry-login.conf
+ pass='"***"'
+ podman login -u serviceaccount -p *** default-route-openshift-image-registry.apps.opr-ocp-2.lab --tls-verify=false
Error: logging into "default-route-openshift-image-registry.apps.opr-ocp-2.lab": invalid username/password
+ cleanup
+ kcli delete cluster opr-ocp-2 -y
opr-ocp-2-ctlplane-0 deleted on local!
opr-ocp-2-worker-0 deleted on local!
opr-ocp-2-worker-1 deleted on local!
opr-ocp-2-worker-2 deleted on local!
Deleting directory /root/.kcli/clusters/opr-ocp-2
+ kcli delete network opr-ocp-2 -y
Network opr-ocp-2 deleted
make: *** [Makefile:200: test-e2e-conformance-virtual-ocp-cluster-ci] Error 125
```

**Comment by wizhaoredhat** [comment]
@adrianchiris PTAL

**Comment by SalDaniele** [comment]
Hi @zeeke any insights into why the OCP CI test is failing?

**Comment by bn222** [comment]
LGTM

**Comment by bn222** [comment]
@ykulazhenkov can you PTAL?

**Review by Eoghan1232 — APPROVED** [review]

**Pull request merged**
