### PR TITLE
e2e: Fix Validate ExcludeTopology test leftover

### PR DESCRIPTION
**Pull request by zeeke**
Fix coding errors introduced while refactoring
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/451

cc @adrianchiris

### CODE REVIEW

**Comment by zeeke** [comment]
@adrianchiris , @SchSeba, unfortunately I left over some errors during my last push on previous PR.

Can you please take a look at this?

Sorry for the inconvenience

**Review by SchSeba — APPROVED** [review]

**Comment by e0ne** [comment]
@zeeke  can we get some CI results before merging this?

**Comment by zeeke** [comment]
Hi @e0ne, we are working to run this test suite closer to this repository, but we're still hitting some virtualization challenges.

Attached are reports of running `make test-e2e-conformance` against an OpenShift 4.13 cluster, on `master` and `pr` branch, focusing on `ExcludeTopology` testcases


[master.output.txt](https://github.com/k8snetworkplumbingwg/sriov-network-operator/files/12237794/master.output.txt)
[master_unit_report.xml.txt](https://github.com/k8snetworkplumbingwg/sriov-network-operator/files/12237801/master_unit_report.xml.txt)
[pr.output.txt](https://github.com/k8snetworkplumbingwg/sriov-network-operator/files/12237805/pr.output.txt)
[pr_unit_report.xml.txt](https://github.com/k8snetworkplumbingwg/sriov-network-operator/files/12237809/pr_unit_report.xml.txt)


This PR fixes
```
• [FAILED] [77.393 seconds]
[sriov] operator Custom SriovNetworkNodePolicy Configuration ExcludeTopology [It] field is forwarded to the device plugin configuration
/home/apanatto/dev/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/test_sriov_operator.go:1444

  [FAILED] Timed out after 30.000s.
  Expected
      <map[string]string | len:2>: {
          "dhcp19-17-171.clus2.t5g.lab.eng.bos.redhat.com": "{\"resourceList\":null}",
          "cnfdd5.clus2.t5g.lab.eng.bos.redhat.com": "{\"resourceList\":[{\"resourceName\":\"resourceXXX\",\"selectors\":{\"pfNames\":[\"eno2np1#0-4\"],\"IsRdma\":false,\"NeedVhostNet\":false},\"SelectorObj\":null}]}",
      }
  to have {key: value} matching
      <map[interface {}]interface {} | len:1>: {
          <string>"cnfdd5.clus2.t5g.lab.eng.bos.redhat.com": <*matchers.ContainSubstringMatcher | 0xc000874ba0>{
              Substr: "{\"resourceName\":\"resourceXXX\",\"excludeTopology\":true,\"selectors\":{\"pfNames\":[\"eno2np1#0-4\"],\"IsRdma\":false,\"NeedVhostNet\":false},\"SelectorObj\":null}",
              Args: nil,
          },
      }
  In [It] at: /home/apanatto/dev/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/test_sriov_operator.go:2244 @ 08/02/23 10:08:37.741
```

**Comment by e0ne** [comment]
@zeeke  thanks for the information!

**Review by e0ne — APPROVED** [review]

**Pull request merged**
